
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/nik/Downloads/clion-2025.1.3/bin/cmake/linux/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.2.0-26-generic - x86_64
...
